### ISSUE TITLE
Encountered error while exporting nested list to parquet file format using pg2parquet utility

### ISSUE THREAD

**Issue by guptashreyaa** [exyi/pg2parquet#22]
Encountered below error:
`thread 'main' panicked at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-postgres-0.7.10/src/row.rs:151:25:
error retrieving column 1: error deserializing column 1: array contains too many dimensions
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
pg2parquet probably should not crash in this way, could you please report a bug at https://github.com/exyi/pg2parquet/issues/new (ideally with the backtrace and some info on what you did)?`

Below is the schema of the table:
`Schema: root
 * OPTIONAL id: INT32
 * OPTIONAL nested_list (List)
	 * REPEATED list
		 * OPTIONAL element: INT32
 * OPTIONAL nested_map: BYTE_ARRAY (String)
 * OPTIONAL list_within_map: BYTE_ARRAY (String)
 * OPTIONAL json_data: BYTE_ARRAY (String)
 * OPTIONAL list_of_json (List)
	 * REPEATED list
		 * OPTIONAL element: BYTE_ARRAY (String)
 * OPTIONAL bson_data: BYTE_ARRAY
 * OPTIONAL list_of_bson (List)
	 * REPEATED list
		 * OPTIONAL element: BYTE_ARRAY`

**Comment by exyi** [comment]
Thanks for reporting the issue. I think it is because some of lists is multi-dimensional, which wasn't supported by pg2parquet. I added the support, it is in version 0.1.1. Note that the dimensionality is dropped during the export, as Parquet lists must have a single-dimension.

Could you please verify that it indeed resolves your issue?
